### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by xwasoux** [TeamKuOn/Concordia#4]
# Sensing Unit (Concordia)

### SPI connection
+ [ ] CAN Module (MCP2515)          :calendar:Waiting(2022/09/10)
+ [ ] MicroSD Card Adapter          :calendar:Waiting(2022/09/10) 

### UART connection
+ [ ] IMU (HWT905-TTL)              :calendar:Start(2022/09/10)
+ [ ] GPS Module (NEO-6M)           :calendar:Start(2022/09/10)

### I2C connection
+ [ ] Air-speed meter (MS4525DO)    :calendar:Waiting(2022/09/10)

### Digital pin connection
+ [ ] Temperature Sensor (DHT11)    :calendar:Waiting(2022/09/10)

# Media Unit (Raspberry Pi4)
+ [ ] CAN Module (MCP2515)          :calendar:Waiting(2022/09/10)
